In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('movies_metadata.csv')

In [3]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [4]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  str
 1   belongs_to_collection  4494 non-null   str
 2   budget                 45466 non-null  str
 3   genres                 45466 non-null  str
 4   homepage               7782 non-null   str
 5   id                     45466 non-null  str
 6   imdb_id                45449 non-null  str
 7   original_language      45455 non-null  str
 8   original_title         45466 non-null  str
 9   overview               44512 non-null  str
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  str
 12  production_companies   45463 non-null  str
 13  production_countries   45463 non-null  str
 14  release_date           45379 non-null  str
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  str
 18  status                 45379 non-null  str
 19  tagline                20412 non-null  str
 20  title                  45460 non-null  str
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(2), str(18)
memory usage: 38.8+ MB

In [6]:
df.shape

(45466, 24)

In [7]:
df.tail

<bound method NDFrame.tail of        adult                              belongs_to_collection    budget  \
0      False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
1      False                                                NaN  65000000
2      False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
3      False                                                NaN  16000000
4      False  {'id': 96871, 'name': 'Father of the Bride Col...         0
...      ...                                                ...       ...
45461  False                                                NaN         0
45462  False                                                NaN         0
45463  False                                                NaN         0
45464  False                                                NaN         0
45465  False                                                NaN         0

                                                  genres  \
0      [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1      [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2      [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3      [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                         [{'id': 35, 'name': 'Comedy'}]
...                                                  ...
45461  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
45462                      [{'id': 18, 'name': 'Drama'}]
45463  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
45464                                                 []
45465                                                 []

                                   homepage      id    imdb_id  \
0      http://toystory.disney.com/toy-story     862  tt0114709
1                                       NaN    8844  tt0113497
2                                       NaN   15602  tt0113228
3                                       NaN   31357  tt0114885
4                                       NaN   11862  tt0113041
...                                     ...     ...        ...
45461  http://www.imdb.com/title/tt6209470/  439050  tt6209470
45462                                   NaN  111109  tt2028550
45463                                   NaN   67758  tt0303758
45464                                   NaN  227506  tt0008536
45465                                   NaN  461257  tt6980792

      original_language               original_title  \
0                    en                    Toy Story
1                    en                      Jumanji
2                    en             Grumpier Old Men
3                    en            Waiting to Exhale
4                    en  Father of the Bride Part II
...                 ...                          ...
45461                fa                      رگ خواب
45462                tl          Siglo ng Pagluluwal
45463                en                     Betrayal
45464                en          Satana likuyushchiy
45465                en                     Queerama

                                                overview  ... release_date  \
0      Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30
1      When siblings Judy and Peter discover an encha...  ...   1995-12-15
2      A family wedding reignites the ancient feud be...  ...   1995-12-22
3      Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22
4      Just when George Banks has recovered from his ...  ...   1995-02-10
...                                                  ...  ...          ...
45461        Rising and falling between a man and woman.  ...          NaN
45462  An artist struggles to finish his work while a...  ...   2011-11-17
45463  When one of her hits goes wrong, a professiona...  ...   2003-08-01
45464  In a small town live two brothers, one a minis...  ...   1917-10-21
45465  50 years after decriminalisation of homosexual...  ...   2017-06-09

           revenue runtime                                   spoken_languages  \
0      373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]
1      262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2              0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]
3       81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]
4       76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]
...            ...     ...                                                ...
45461          0.0    90.0             [{'iso_639_1': 'fa', 'name': 'فارسی'}]
45462          0.0   360.0                  [{'iso_639_1': 'tl', 'name': ''}]
45463          0.0    90.0           [{'iso_639_1': 'en', 'name': 'English'}]
45464          0.0    87.0                                                 []
45465          0.0    75.0           [{'iso_639_1': 'en', 'name': 'English'}]

         status                                            tagline  \
0      Released                                                NaN
1      Released          Roll the dice and unleash the excitement!
2      Released  Still Yelling. Still Fighting. Still Ready for...
3      Released  Friends are the people who let you be yourself...
4      Released  Just When His World Is Back To Normal... He's ...
...         ...                                                ...
45461  Released         Rising and falling between a man and woman
45462  Released                                                NaN
45463  Released                             A deadly game of wits.
45464  Released                                                NaN
45465  Released                                                NaN

                             title  video vote_average vote_count
0                        Toy Story  False          7.7     5415.0
1                          Jumanji  False          6.9     2413.0
2                 Grumpier Old Men  False          6.5       92.0
3                Waiting to Exhale  False          6.1       34.0
4      Father of the Bride Part II  False          5.7      173.0
...                            ...    ...          ...        ...
45461                       Subdue  False          4.0        1.0
45462          Century of Birthing  False          9.0        3.0
45463                     Betrayal  False          3.8        6.0
45464             Satan Triumphant  False          0.0        0.0
45465                     Queerama  False          0.0        0.0

[45466 rows x 24 columns]>

In [8]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [9]:
df = df.drop_duplicates().reset_index(drop = True)

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df = df[['title', 'overview', 'genres','tagline','vote_average','popularity']]

In [12]:
df

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519
...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",Rising and falling between a man and woman,4.0,0.072051
45449,Century of Birthing,An artist struggles to finish his work while a...,"[{'id': 18, 'name': 'Drama'}]",NaN,9.0,0.178241
45450,Betrayal,"When one of her hits goes wrong, a professiona...","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",A deadly game of wits.,3.8,0.903007
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",[],NaN,0.0,0.003503
45452,Queerama,50 years after decriminalisation of homosexual...,[],NaN,0.0,0.163015

In [13]:
df.isnull().sum()

title               6
overview          954
genres              0
tagline         25045
vote_average        6
popularity          5
dtype: int64

In [14]:
df = df.dropna(subset=['title'])

In [15]:
df['overview'] = df['overview'].fillna('')

In [16]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [17]:
import ast
df['genres'] = df['genres'].apply(lambda x :" ".join([i['name'] for i in ast.literal_eval(x)]))

In [18]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [19]:
df['tagline'] = df['tagline'].fillna('')

In [20]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [21]:
df['tags'] = df['overview']+ " " + df['genres'] +" "+ df['tagline']

In [22]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [23]:
df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [24]:
df['tags'][2]

"A family wedding reignites the ancient feud between next-door neighbors and fishing buddies John and Max. Meanwhile, a sultry Italian divorcée opens a restaurant at the local bait shop, alarming the locals who worry she'll scare the fish away. But she's less interested in seafood than she is in cooking up a hot time with Max. Romance Comedy Still Yelling. Still Fighting. Still Ready for Love."

In [25]:
df['tags'][3]

'Cheated on, mistreated and stepped on, the women are holding their breath, waiting for the elusive "good man" to break a string of less-than-stellar lovers. Friends and confidants Vannah, Bernie, Glo and Robin talk it all out, determined to find a better way to breathe. Comedy Drama Romance Friends are the people who let you be yourself... and never let you forget it.'

In [26]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [27]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rames\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\rames\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [28]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [29]:
def preprocess_text(text):
  #lowercase
  text = str(text).lower()
  #removed the punctuations
  text = re.sub(r'[^a-zA-Z\s]', '', text)

  words = text.split()
  #remove stopwords
  words = [word for word in words if word not in stop_words]

  #lemmatize
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

In [30]:
df['tags'] = df['tags'].apply(preprocess_text)

In [33]:
df["tags"][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [35]:
df["tags"][2]

'family wedding reignites ancient feud nextdoor neighbor fishing buddy john max meanwhile sultry italian divorce open restaurant local bait shop alarming local worry shell scare fish away shes less interested seafood cooking hot time max romance comedy still yelling still fighting still ready love'

In [36]:
df = df.reset_index(drop = True)

In [37]:
indices = pd.Series(df.index,index = df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [39]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [40]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [43]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1548114 stored elements and shape (45447, 50000)>

# Cosine similarity measures the similarity between two non-zero vectors by calculating the cosine of the angle between them

In [44]:
from sklearn.metrics.pairwise import cosine_similarity

In [50]:
def recommend(title, n = 10):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [51]:
recommend('Avatar',5)

26547                  Avatar 2
13883      The Inhabited Island
26553            Thor: Ragnarok
43431    Moontrap: Target Earth
14119      The Three Musketeers
Name: title, dtype: str

In [56]:
recommend('Toy Story')

2996                Toy Story 2
15344               Toy Story 3
24512                 Small Fry
28972           Superstar Goofy
17184                 Group Sex
6434     What's Up, Tiger Lily?
11396    For Your Consideration
1071      Rebel Without a Cause
1931                  Condorman
485                      Malice
Name: title, dtype: str

In [58]:
recommend("Group Sex")

26004               The Single Moms Club
0                              Toy Story
28703                              Hotel
38210                       The Neighbor
10017                  Between Your Legs
32092                              Ultrà
4455                      The Dream Team
30646                Five Element Ninjas
6973     The Killing of a Chinese Bookie
30708                   Stripper Academy
Name: title, dtype: str

In [61]:
recommend("GoldenEye")

5657                      Casino Royale
7329                          Octopussy
2872                 For Your Eyes Only
2874                   Live and Let Die
2262                   A View to a Kill
3516        The Man with the Golden Gun
2873                    Licence to Kill
7332              Never Say Never Again
3858               Diamonds Are Forever
3510    On Her Majesty's Secret Service
Name: title, dtype: str

In [62]:
recommend("GoldenEye",5)

5657         Casino Royale
7329             Octopussy
2872    For Your Eyes Only
2874      Live and Let Die
2262      A View to a Kill
Name: title, dtype: str

In [63]:
import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))

pickle.dump(indices,open('indices.pkl','wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf,open('tfidf.pkl','wb'))